"""new fields in User model

Revision ID: 763bf5a9b05f
Revises: d7c25a0838af
Create Date: 2019-12-20 12:37:44.106827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763bf5a9b05f'
down_revision = 'd7c25a0838af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
