"""add language field to Post

Revision ID: 780c718133bd
Revises: 93bb89a5f374
Create Date: 2019-12-22 11:48:41.073671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780c718133bd'
down_revision = '93bb89a5f374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
